# Generated by Django 4.2.5 on 2023-09-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="UserProfile",),
    ]
