# Generated by Django 4.2.5 on 2023-09-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0004_orders_orderupdate"),
    ]

    operations = [
        migrations.RenameModel(old_name="RoomType", new_name="Product",),
        migrations.RenameField(
            model_name="product", old_name="room_name", new_name="product_name",
        ),
    ]
