# Generated by Django 4.2.5 on 2023-09-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerceapp",
            "0007_roomtype_image1_roomtype_image2_roomtype_image3_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="image6",
            field=models.ImageField(default="", upload_to="images/additional-images"),
        ),
    ]
