# Generated by Django 4.2.5 on 2023-09-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0012_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(name="UserProfile",),
    ]
