# Generated by Django 4.2.5 on 2023-09-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0013_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="booking_date",
            field=models.DateField(default= "2023-9-27" , max_length=50),
        ),
    ]
