# Generated by Django 4.2.5 on 2023-09-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0018_orders_appointment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="appointment_date",
            field=models.CharField(default="", max_length=50),
        ),
    ]
