# Generated by Django 4.2.5 on 2023-09-27 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0019_alter_orders_appointment_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="appointment_date",),
    ]
