# Generated by Django 4.2.5 on 2023-09-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0020_remove_orders_appointment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="appointment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
