# Generated by Django 4.2.5 on 2023-09-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0023_payment"),
    ]

    operations = [
        migrations.DeleteModel(name="Payment",),
        migrations.AddField(
            model_name="orders",
            name="payment_status",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="orders",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
