# Generated by Django 4.1.11 on 2023-10-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0024_delete_payment_orders_payment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="has_food_facility",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="has_swimming_pool",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="near_airport",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="sea_area",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="vacancies",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
