# Generated by Django 4.1.11 on 2023-10-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0025_roomtype_has_food_facility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="checkin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="checkout",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="member_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="members",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
