# Generated by Django 4.1.11 on 2023-10-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0027_remove_orders_checkin_remove_orders_checkout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="id_proof",
            field=models.ImageField(blank=True, null=True, upload_to="id_proofs/"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="address2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
