# Generated by Django 4.1.11 on 2023-10-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0028_orders_id_proof_alter_orders_address2"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("age", models.IntegerField()),
                ("aadhar", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200)),
                (
                    "id_proof",
                    models.ImageField(
                        blank=True, null=True, upload_to="member_id_proofs/"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="orders",
            name="member_json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="members",
            field=models.ManyToManyField(to="ecommerceapp.memberdetails"),
        ),
    ]
