# Generated by Django 4.1.11 on 2023-10-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0029_memberdetails_orders_member_json_orders_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="aadhar",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="age",
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="mobile",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
