# Generated by Django 4.1.11 on 2023-10-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0030_orders_aadhar_orders_age_orders_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
