# Generated by Django 4.1.11 on 2023-10-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0031_alter_orders_age"),
    ]

    operations = [
        migrations.DeleteModel(name="OrderUpdate",),
    ]
