# Generated by Django 4.1.11 on 2023-10-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0032_delete_orderupdate"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="members",),
        migrations.DeleteModel(name="MemberDetails",),
    ]
