# Generated by Django 4.1.11 on 2023-10-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0033_remove_orders_members_delete_memberdetails"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="member_json",),
    ]
