# Generated by Django 4.1.11 on 2023-10-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0034_remove_orders_member_json"),
    ]

    operations = [
        migrations.RemoveField(model_name="orders", name="address2",),
        migrations.RemoveField(model_name="orders", name="amountpaid",),
        migrations.RemoveField(model_name="orders", name="oid",),
        migrations.RemoveField(model_name="orders", name="payment_status",),
        migrations.RemoveField(model_name="orders", name="paymentstatus",),
        migrations.RemoveField(model_name="orders", name="phone",),
        migrations.RemoveField(model_name="orders", name="razorpay_order_id",),
        migrations.RemoveField(model_name="orders", name="razorpay_payment_id",),
    ]
