# Generated by Django 4.1.11 on 2023-10-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerceapp",
            "0035_remove_orders_address2_remove_orders_amountpaid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
